language: python
cache: pip
python:
        - "3.6"
        - "3.7"
        - "3.8"
        - "3.9"
install:
        - pip install -r requirements.txt
        - pip install setuptools_scm
        - python setup.py build
script:
        - python -m unittest discover
